services:
  dockge:
    container_name: dockge01
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    image: louislam/dockge:1
    
    restart: unless-stopped
    ports:
      # Host Port : Container Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data

      # If you want to use private registries, you need to share the auth file with Dockge:
      # - /root/.docker/:/root/.docker

      # Stacks Directory
      #  ^z   ^o READ IT CAREFULLY. If you did it wrong, your data could end up writing into a WRONG PATH.
      #  ^z   ^o 1. FULL path only. No relative path (MUST)
      #  ^z   ^o 2. Left Stacks Path === Right Stacks Path (MUST)
      - /opt/stacks:/opt/stacks
    environment:
      # Tell Dockge where is your stacks directory
      - DOCKGE_STACKS_DIR=/opt/stacks
