services:
  dockge:
    container_name: dockge01
    image: louislam/dockge:1    
    restart: unless-stopped
    ports:
      # Host-Port : Container-Port
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/app/data

      # Wenn Sie private Registrierungen verwenden möchten, müssen Sie die Autorisierungsdatei mit Dockge teilen:
      # - /root/.docker/:/root/.docker

      # Stapel-Verzeichnis
      #  ^z   ^o SORGFÄLTIG LESEN. Wenn Sie etwas falsch machen, könnten Ihre Daten in einen FALSCHEN PFAD geschrieben werden.
      #  ^z   ^o 1. Nur vollständiger Pfad. Kein relativer Pfad (PFLICHT)
      #  ^z   ^o 2. Pfad des linken Stapels === Pfad des rechten Stapels (PFLICHT)
      - /opt/stacks:/opt/stacks
    environment:
      # Informieren Sie Dockge, wo sich Ihr Stack-Verzeichnis befindet
      - DOCKGE_STACKS_DIR=/opt/stacks
