version: "3.3"
services:
  watchtower:
    container_name: watchtower
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # Zeitzone des Systems nutzen
      # /etc/localtime:/etc/localtime:ro
    environment:
      # Zeitzone (Central European Time)
      - TZ=CET
      # Aufrufintervall in Sekunden (21600 Sek. = 360 Min. = 6 Std.)
      - WATCHTOWER_POLL_INTERVAL=21600
      # Nur überwachen / keine Aktualisierung
      - WATCHTOWER_MONITOR_ONLY=false
      # Benachrichtigungs-Level
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      # Benachrichtigungs-Hostname
      - WATCHTOWER_NOTIFICATIONS_HOSTNAME=
      # Benachrichtigungs-Verzögerung
      - WATCHTOWER_NOTIFICATIONS_DELAY=
      # Benachrichtigungs-Titel
      - WATCHTOWER_NOTIFICATION_TITLE_TAG=Watchtower
    depends_on: []
networks: {}
x-dockge:
  urls:
    - https://containrrr.dev/watchtower/
    - https://github.com/containrrr/watchtower
