version: "3.3"
services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:26.0.0
    command: start-dev
    ports:
      - 8080:8080
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
networks: {}
x-dockge:
  urls:
    - https://www.keycloak.org/
